backend:
  name: git-gateway
  branch: main
publish_mode: simple # or editorial_workflow
media_folder: assets
public_folder: /
#site_url: https://statidocs.cecil.app
editor:
  preview: false

collections:
  - name: docs
    label: Docs
    label_singular: Docs page
    folder: pages/docs
    identifier_field: title
    path: '{{group}}/{{slug}}'
    create: true
    summary: '{{group}} > {{title}}'
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Group, name: group, widget: string }
      - { label: Body, name: body, widget: markdown }
  - name: pages
    label: Pages
    files:
      - label: Home page
        name: index
        file: pages/index.md
        fields:
          - { label: Body, name: body, widget: markdown }
          - label: Home blocks
            name: blocks
            widget: list
            typeKey: name
            types:
              - label: Hero
                name: hero
                widget: object
                summary: '{{fields.baseline}}'
                fields:
                  - { label: Baseline, name: baseline, widget: string, default: 'Baseline' }
                  - { label: Description, name: description, widget: markdown, default: 'Description' }
              - label: CTA
                name: cta
                widget: object
                summary: '{{fields.baseline}}'
                fields:
                  - label: Button
                    name: button
                    widget: relation
                    collection: docs
                    search_fields: ['title']
                    value_field: '{{slug}}'
                    display_fields: ['title']
                  - { label: Link, name: link, widget: string }
              - label: Features
                name: features
                widget: list
                summary: '{{fields.title}}'
                fields:
                  - { label: Title, name: title, widget: string, default: 'Title' }
                  - { label: Description, name: description, widget: markdown, default: 'Description' }
      - label: About
        name: about
        file: pages/about.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Menu, name: menu, widget: string }
          - { label: Body, name: body, widget: markdown }
