backend:
  name: git-gateway
  branch: main
publish_mode: simple # editorial_workflow
media_folder: assets
public_folder: /
site_url: https://statidocs.cecil.app

#i18n:
#  structure: multiple_files
#  locales: [en, fr]
#  default_locale: en

collections:
  - name: docs
    label: Docs
    label_singular: Docs page
    folder: pages/docs
    identifier_field: title
    path: '{{dirname}}/{{slug}}'
    create: true
    i18n: true
    summary: '{{dirname}} > {{title}}'
    preview_path: docs/{{slug}}
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: pages
    label: Pages
    files:
      - label: About
        name: about
        file: pages/about.md
        i18n: true
        fields:
          - { label: "Title", name: "title", widget: "string", i18n: true }
          - { label: "Menu", name: "menu", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: Home page
        name: index
        file: pages/index.md
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
